/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui.logindanregist;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class utama extends javax.swing.JFrame {

    /**
     * Creates new form utama
     */
    DefaultTableModel model;
    int index, confirm;
    String noresi,
           namapengirim,
           namapenerima,
           nopengirim,
           nopenerima,
           alamatpengirim,
           alamatpenerima,
           jenislayanan,
           statuspengiriman,
           detailpaket;
          
           
    
    public utama() {
        initComponents();
    
    
        Object kolom[] = {"no.resi", "nama pengirim", "no.pengirim", "alamat pengirim", "nama penerima", "no.penerima", "alamat penerima", "jenis layanan", "status", "detail"};
        Object data[][] = {};
        
        model = new DefaultTableModel(data, kolom);
        jTablehasil.setModel(model);
        
//       JOptionPane.showMessageDialog(this, "selamat datang di Aplikasi PAKETMU", "informasi !", JOptionPane.INFORMATION_MESSAGE);
//        JOptionPane.showMessageDialog(this, "Silahkan isi tabel", "informasi !", JOptionPane.INFORMATION_MESSAGE);
    }       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupjenislayanan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnamapengirim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnamapenerima = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnopengirim = new javax.swing.JTextField();
        txtnopenerima = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaalamatpengirim = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaalamatpenerima = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtnoresi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreadetailpaket = new javax.swing.JTextArea();
        jcbstatuspengiriman = new javax.swing.JComboBox<>();
        jRadioButtonreguler = new javax.swing.JRadioButton();
        jRadioButtonexpress = new javax.swing.JRadioButton();
        jRadioButtonsameday = new javax.swing.JRadioButton();
        jRadioButtoninstant = new javax.swing.JRadioButton();
        btnsimpan = new javax.swing.JButton();
        btnhapusinput = new javax.swing.JButton();
        btnhapusisi = new javax.swing.JButton();
        btnhapusbaris = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablehasil = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PAKETKU");

        jLabel2.setText("NAMA PENGIRIM");

        jLabel3.setText("NAMA PENERIMA");

        jLabel4.setText("NO.PENGIRIM");

        jLabel5.setText("NO.PENERIMA");

        jLabel6.setText("ALAMAT PENGIRIM");

        jLabel7.setText("ALAMAT PENERIMA");

        jTextAreaalamatpengirim.setColumns(20);
        jTextAreaalamatpengirim.setRows(5);
        jScrollPane1.setViewportView(jTextAreaalamatpengirim);

        jTextAreaalamatpenerima.setColumns(20);
        jTextAreaalamatpenerima.setRows(5);
        jScrollPane2.setViewportView(jTextAreaalamatpenerima);

        jLabel8.setText("NO.RESI");

        txtnoresi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoresiActionPerformed(evt);
            }
        });

        jLabel9.setText("JENIS LAYANAN");

        jLabel10.setText("STATUS PENGIRIMAN");

        jLabel11.setText("DETAIL PAKET");

        jTextAreadetailpaket.setColumns(20);
        jTextAreadetailpaket.setRows(5);
        jScrollPane3.setViewportView(jTextAreadetailpaket);

        jcbstatuspengiriman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PESANAN DIBUAT", "PAKET DIJEMPUT EKSPEDISI", "DALAM PERJALANAN", "SEDANG DIKIRIM", "PAKET DITERIMA", "TERTUNDA", "RETURN", " " }));

        groupjenislayanan.add(jRadioButtonreguler);
        jRadioButtonreguler.setText("REGULER");

        groupjenislayanan.add(jRadioButtonexpress);
        jRadioButtonexpress.setText("EXPRESS");

        groupjenislayanan.add(jRadioButtonsameday);
        jRadioButtonsameday.setText("SAME DAY");

        groupjenislayanan.add(jRadioButtoninstant);
        jRadioButtoninstant.setText("INSTANT");

        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnhapusinput.setText("HAPUS INPUT");
        btnhapusinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusinputActionPerformed(evt);
            }
        });

        btnhapusisi.setText("HAPUS ISI");
        btnhapusisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusisiActionPerformed(evt);
            }
        });

        btnhapusbaris.setText("HAPUS BARIS");
        btnhapusbaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusbarisActionPerformed(evt);
            }
        });

        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        jTablehasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "no.resi", "nama pengirim", "no.pengirim", "alamat pengirim", "nama penerima", "no.penerima", "alamat penerima", "jenis layanan", "status", "detail"
            }
        ));
        jScrollPane4.setViewportView(jTablehasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtnopengirim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnamapengirim, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnopenerima, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnamapenerima)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnhapusbaris)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnkeluar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonexpress, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonsameday, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonreguler, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtoninstant, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jcbstatuspengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(160, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnoresi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnsimpan)
                        .addGap(33, 33, 33)
                        .addComponent(btnhapusinput)
                        .addGap(33, 33, 33)
                        .addComponent(btnhapusisi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnoresi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtnamapengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtnamapenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnopengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnopenerima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonreguler)
                                    .addComponent(jRadioButtoninstant))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonexpress)
                                    .addComponent(jRadioButtonsameday))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnsimpan)
                                    .addComponent(btnhapusinput)
                                    .addComponent(btnhapusisi)
                                    .addComponent(btnhapusbaris)
                                    .addComponent(btnkeluar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jcbstatuspengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnoresiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoresiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoresiActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:

//      data pelanggan
      noresi = txtnoresi.getText();
      namapengirim = txtnopengirim.getText();
      namapenerima = txtnamapenerima.getText();
      nopengirim = txtnopengirim.getText();
      nopenerima = txtnopenerima.getText();
      alamatpengirim = jTextAreaalamatpengirim.getText();
      alamatpenerima = jTextAreaalamatpenerima.getText();
      
      
//      data barang
      statuspengiriman = jcbstatuspengiriman.getSelectedItem().toString();
      detailpaket = jTextAreadetailpaket.getText();
      
//      jenis layanan
      if (jRadioButtonreguler.isSelected()) {
             jenislayanan = "Reguler";
      } else if (jRadioButtoninstant.isSelected()) {
            jenislayanan = "Instant";
      } else if (jRadioButtonexpress.isSelected()) {
            jenislayanan = "Express";
      } else if (jRadioButtonsameday.isSelected()) {
            jenislayanan = "Same day";
      } 
      
      statuspengiriman = jcbstatuspengiriman.getSelectedItem().toString();
      
//         masukkan ke tabel
      confirm = JOptionPane.showConfirmDialog(this,"apakah sudah yakin benar ?",
                "konfirmasi !", JOptionPane.YES_NO_OPTION);
      if (confirm == JOptionPane.YES_OPTION) {
          model.addRow(new Object[] {
              noresi,
              namapengirim,
              namapenerima,
              nopengirim,
              nopenerima,
              alamatpengirim,
              alamatpenerima,
              jenislayanan,
              statuspengiriman,
              detailpaket});
          JOptionPane.showMessageDialog(this, "data berhasil ditambah", "informasi !", JOptionPane.INFORMATION_MESSAGE);
      }
    
    
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        confirm = JOptionPane.showConfirmDialog(this, "apakah yakin keluar dari program ?",
                    "konfirmasi !", JOptionPane.YES_OPTION);
        if (confirm == JOptionPane.YES_NO_OPTION){;
            dispose();
            JOptionPane.showMessageDialog(this, "terima kasih !", "informasi !", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnhapusinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusinputActionPerformed
        // TODO add your handling code here:
        confirm = JOptionPane.showConfirmDialog(this,"anda yakin untuk hapus input ?",
                    "konfirmasi !", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {;
            txtnoresi.setText("");
            txtnamapengirim.setText("");
            txtnamapenerima.setText("");
            txtnopengirim.setText("");
            txtnamapenerima.setText("");
            jTextAreaalamatpengirim.setText("");
            jTextAreaalamatpenerima.setText("");
            jcbstatuspengiriman.setSelectedItem("none");
            jTextAreadetailpaket.setText("");
            groupjenislayanan.clearSelection();
            JOptionPane.showMessageDialog(this,"input berhasil dihapus !", "informasi !", JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_btnhapusinputActionPerformed

    private void btnhapusbarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusbarisActionPerformed
        // TODO add your handling code here:
        confirm = JOptionPane.showConfirmDialog(this, "apakah yakin mengapus baris ?",
                    "konfirmasi !", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {;
        index = jTablehasil.getSelectedRow();
        model.removeRow(index);
        jTablehasil.setModel(model);
        JOptionPane.showMessageDialog(this, "data berhasil dihapus !", "informasi !", JOptionPane.INFORMATION_MESSAGE);
        
        }
    }//GEN-LAST:event_btnhapusbarisActionPerformed

    private void btnhapusisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusisiActionPerformed
        // TODO add your handling code here:
        confirm = JOptionPane.showConfirmDialog(this, "apakah yakin menghapus semua data ?",
                    "konfirmasi !", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            model.setRowCount(0); //menghapus semua isi dari tabel
            JOptionPane.showMessageDialog(this, "semua data berhasil dihapus !", "informasi !", JOptionPane.INFORMATION_MESSAGE);
            
            
        }
    }//GEN-LAST:event_btnhapusisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapusbaris;
    private javax.swing.JButton btnhapusinput;
    private javax.swing.JButton btnhapusisi;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.ButtonGroup groupjenislayanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonexpress;
    private javax.swing.JRadioButton jRadioButtoninstant;
    private javax.swing.JRadioButton jRadioButtonreguler;
    private javax.swing.JRadioButton jRadioButtonsameday;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTablehasil;
    private javax.swing.JTextArea jTextAreaalamatpenerima;
    private javax.swing.JTextArea jTextAreaalamatpengirim;
    private javax.swing.JTextArea jTextAreadetailpaket;
    private javax.swing.JComboBox<String> jcbstatuspengiriman;
    private javax.swing.JTextField txtnamapenerima;
    private javax.swing.JTextField txtnamapengirim;
    private javax.swing.JTextField txtnopenerima;
    private javax.swing.JTextField txtnopengirim;
    private javax.swing.JTextField txtnoresi;
    // End of variables declaration//GEN-END:variables
}
